### PR TITLE
fix the problem on the Windows

### LINKED ISSUE #8: Version >= 0.4.0 does not work with Windows
This is related to an issue with mio.

This issue is related to https://github.com/carllerche/mio/issues/411

### PR DESCRIPTION
**Pull request by Covertness**
Fix #8 . Replace the tx_thread with the writable event.

### CODE REVIEW

**Comment by Covertness** [comment]
@jamesmunns I have removed the tx_thread and response the client when the writable happened
. Please tell me if you have any question.

File: src/server.rs [hunk 1]
```diff
@@ -220,27 +233,37 @@ impl CoAPServer {
...
+    match tx_recv.recv() {
+        Ok(q_res) => {
+            match q_res.response {
+                Some(resp) => {
+                    match resp.message.to_bytes() {
+                        Ok(bytes) => {
+                            match tx_only.send_to(&bytes[..], &q_res.address) {
+                                Ok(None) => {
+                                    // Look at https://github.com/carllerche/mio/issues/411 in detail
+                                    error!("Failed to complete the response");
```
Comment (jamesmunns) [inline src/server.rs]: @Covertness Do we need to requeue the response here, sort of like like on line 122?

If sending the response fails, how do we retry it?

File: src/server.rs [hunk 2]
```diff
@@ -220,27 +233,37 @@ impl CoAPServer {
     }
 }
 
-fn transmit_handler(tx_recv: RxQueue, tx_only: UdpSocket) {
-    // Note! We should only transmit with this UDP Socket
+fn response_handler(tx_recv: &RxQueue, tx_only: &UdpSocket) {
     // TODO: Add better support for failure detection or logging
```
Comment (jamesmunns) [inline src/server.rs]: I think we can remove this comment now, though we should probably consider how to flatten this block out. It gets nested pretty deeply here.

File: src/server.rs (hunk 1 above)
Comment (Covertness) [inline src/server.rs]: @jamesmunns simply requeue may be result in infinite loop. When a writable event emitted, I think send_to should be succeeded.

File: src/server.rs (hunk 2 above)
Comment (Covertness) [inline src/server.rs]: Yeah. I will think about it. And I think the thread_pool isn't needed any more. Because the event pool is a single thread, and the writable event will be emitted one by one.

**Comment by Covertness** [comment]
The thread pool has been removed. And I refactor some codes. Ready to merge.
